fix: correct javascript error
PaulBernier/factom-identity pull request #3
Opened 2019-12-24 01:39 UTC by mica16

Major error: `getActiveKeysAtHeight` is not a function but an instance method.

fixed, + some auto-indentation with IntelliJ.

2019-12-24 17:25 UTC, PaulBernier requested changes
Oops that's bad, seems this part didn't get refactored properly, thanks for catching that.

2019-12-24 17:25 UTC, PaulBernier commented on src/app/factom-identity-manager.js
> +            this.cli,
this param is not necessary anymore

2019-12-24 17:25 UTC, PaulBernier commented on src/app/identity-management.js
> +    const activeKeys = await identityRetriever.getActiveKeysAtHeight(cli, identityChainId);
getActiveKeysAtHeight doesn't take `cli` as its first argument, just `identityChainId`

2019-12-24 17:25 UTC, PaulBernier commented on src/app/identity-management.js
> +    const activeKeys = await identityRetriever.getActiveKeysAtHeight(cli, identityChainId);
Also the incorrect import of `getActiveKeysAtHeight` at the top of this file can be removed

2019-12-25 11:42 UTC, mica16 commented
Right, it was due to wrong copy paste between the project I'm working on and this fork.

You say that cli is not used any more within replaceIdentityKey but this one makes a final call using it: return cli.add(entry, ecAddress);

May you valid this PR and merge it if it is ASAP?

Thank you!

2019-12-25 23:05 UTC, PaulBernier approved these changes

2019-12-25 23:06 UTC, merged

2019-12-25 23:16 UTC, PaulBernier commented
Published on npm with version 0.2.1. Thanks!

2019-12-25 23:40 UTC, mica16 commented
Thanks :)